CREATE TABLE manager
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_manager PRIMARY KEY (id)
);

comment on table manager is 'Предприятие';
comment on column manager.id is 'Уникальный идентификатор записи';
comment on column manager.name is 'Наименование предприятия';
comment on column manager.password is 'Пароль';