CREATE TABLE ride
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY primary key,
    vehicle_id INTEGER,
    dt_start   TIMESTAMP with time zone,
    dt_end     TIMESTAMP with time zone
);

ALTER TABLE ride
    ADD CONSTRAINT FK_RIDE_ON_VEHICLE FOREIGN KEY (vehicle_id) REFERENCES vehicle (id);

comment on table ride is 'Поездка';
comment on column ride.id is 'Уникальный идентификатор записи';
comment on column ride.vehicle_id is 'Ссылка на автомобиль';
comment on column ride.dt_start is 'Дата и время начала поездки';
comment on column ride.dt_end is 'Дата и время окончания поездки';