create table vehicle_track
(
    id          int GENERATED BY DEFAULT AS IDENTITY primary key,
    vehicle_id  bigint,
    coordinates geometry(Point,4326)
);

comment on table vehicle_track is 'Маршрут';
comment on column vehicle_track.id is 'Уникальный идентификатор записи';
comment on column vehicle_track.vehicle_id is 'Ссылка на автомобиль';
comment on column vehicle_track.coordinates is 'Координаты точки';