create table vehicle
(
    id               int GENERATED BY DEFAULT AS IDENTITY primary key,
    price            bigint,
    year_manufacture varchar(255)
);

comment on table vehicle is 'Автомобиль';
comment on column vehicle.id is 'Уникальный идентификатор записи';
comment on column vehicle.price is 'Стоимость автомобиля';
comment on column vehicle.year_manufacture is 'Год выпуска';