create table brand
(
    id            int GENERATED BY DEFAULT AS IDENTITY primary key,
    name_brand    varchar(255),
    machine_type  varchar(255),
    tank          varchar(255),
    load_capacity varchar(255),
    seats_number  int
);

comment on table brand is 'Бренд';
comment on column brand.id is 'Уникальный идентификатор записи';
comment on column brand.name_brand is 'Имя бренда';
comment on column brand.machine_type is 'Тип машины';
comment on column brand.tank is 'Бак';
comment on column brand.load_capacity is 'Грузоподъемность';
comment on column brand.seats_number is 'Количество мест';