version: '3'
services:

  car-park-db:
    container_name: car-park-db
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - $HOME/car-park/db/:/var/lib/postgresql/data
    networks:
      - car-park

  car-park:
    container_name: car-park
    image: ghcr.io/leolasland/car-park/car-park:latest
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5505
      SPRING_DATASOURCE_URL: jdbc:postgresql://car-park-db:5432/postgres
    depends_on:
      - car-park-db
    ports:
      - "80:8080"
    networks:
      - car-park

networks:
  car-park:
