name: Deploy
on: workflow_dispatch
jobs:
  deploy:
    name: "Deploy to test stand"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/test-stand.key
          chmod 600 ~/.ssh/test-stand.key
          cat >>~/.ssh/config <<END
          Host test-stand
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/test-stand.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.STAND_SSH_USER }}
          SSH_KEY: ${{ secrets.STAND_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAND_SSH_HOST }}

      - name: Copy docker-compose.yml
        run: scp -F ~/.ssh/config -i ~/.ssh/test-stand.key car-park/docker-compose-deploy.yml test-stand:docker-compose.yml

      - name: Run docker-compose
        run: ssh test-stand 'docker-compose up -d'
